### ISSUE TITLE
OOM when asciidoc content is indented

### ISSUE THREAD

**Issue by ia3andy** [yupiik/tools-maven-plugin#21]
**Describe the bug**
```
2024-10-30 10:08:47,351 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /hello failed, error id: 0c236cc2-7963-4d75-bd62-910823627275-1: java.lang.OutOfMemoryError: Required length exceeds implementation limit
	at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:265)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:243)
	at java.base/java.lang.AbstractStringBuilder.appendNull(AbstractStringBuilder.java:635)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:584)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
	at io.yupiik.asciidoc.parser.Parser.parseCodeBlock(Parser.java:466)
	at io.yupiik.asciidoc.parser.Parser.doParse(Parser.java:238)
	at io.yupiik.asciidoc.parser.Parser.parseBody(Parser.java:188)
	at io.yupiik.asciidoc.parser.Parser.parseBody(Parser.java:180)
	at io.quarkiverse.qute.web.asciidoc.runtime.AsciidocConverter.apply(AsciidocConverter.java:16)
```
**To Reproduce**
Use this content:
```asciidoc
  The goal of this extension is to expose https://quarkus.io/guides/qute-reference[Qute] templates located in the `src/main/resource/templates/pub` directory via HTTP.
  Automatically, no controllers needed.
  For example, the template `src/main/resource/templates/pub/foo.html` will be served from the paths `/foo` and `/foo.html` by default.

  NOTE: The `index.html` and `index.qute.html` pages are handled specifically, i.e. they are also served as a "default page" of the containing directory. For example, the template `src/main/resource/templates/pub/index.html` will be served from the paths `/index`, `/index.html` and `/` by default.

  == Installation

  If you want to use this extension, you need to add the `io.quarkiverse.qute.web:quarkus-qute-web` extension first to your build file.

  For instance, with Maven, add the following dependency to your POM file:

  {#for name in cdi:foo.names}
    * {name}
  {/}

  [source,xml,subs=attributes+]
  ----
  <dependency>
      <groupId>io.quarkiverse.qute.web</groupId>
      <artifactId>quarkus-qute-web</artifactId>
      <version>\{project-version}</version>
  </dependency>
  ----
```
**Expected behavior**
I am not sure, but no OOM

**Comment by ia3andy** [comment]
Added this locally and it fixes the issue:
```java
public static String trimIndent(String content) {
        int minIndent = Integer.MAX_VALUE;
        boolean foundNonEmptyLine = false;

        // Calculate minimum indentation in a single pass
        final String[] lines = content.split("\\v");
        for (String line : lines) {
            if (!line.trim().isEmpty()) {
                int leadingSpaces = line.indexOf(line.trim());
                minIndent = Math.min(minIndent, leadingSpaces);
                foundNonEmptyLine = true;
            }
        }

        // If no indentation needs removal, or all lines are empty, return original content
        if (!foundNonEmptyLine || minIndent == 0) {
            return content;
        }

        // Build the output with trimmed indent
        StringBuilder result = new StringBuilder();
        for (String line : lines) {
            if (line.length() >= minIndent) {
                result.append(line.substring(minIndent));
            } else {
                result.append(line); // Preserve empty lines as-is
            }
            result.append("\n");
        }

        return result.toString();
    }
 ```

**Comment by fpapon** [comment]
@ia3andy thank you for the issue, I will take a look.

**Comment by rmannibucau** [comment]
just ensure the comparison in https://github.com/yupiik/tools-maven-plugin/blob/master/asciidoc-java/src/main/java/io/yupiik/asciidoc/parser/Parser.java#L465 is trimmed:

> while ((next = reader.nextLine()) != null && !Objects.equals(marker, next.strip())) {

**Comment by fpapon** [comment]
@ia3andy I pushed a PR to fix the issue and add a test. If you have a chance to test from your side it would be great :)

**Comment by fpapon** [comment]
As it's ok from our side, I will merge and run the release process.

**Comment by fpapon** [comment]
@ia3andy the release has been done and the 1.2.4 is available on Central. Let us know if it's ok from your side.
